version: "3.5"
services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: backend-api-gateway
    restart: always
    environment:
      - DEBUG=1
      - INTENT_MANAGER_HOST=http://intent_manager
    ports:
      - "8080:8080"
    networks:
      - internal_network
      - default
  intent_manager:
    build:
      context: ./intent-manager
    container_name: backend-intent-manager
    restart: always
    environment:
      - DEBUG=1
      - DECISION_MAKER_INSTANCES=1
      - POLICY_GENERATOR_HOST=http://policy_generator
      # credentials of the knowledge base db
      - DATABASE_USER=postgres
      - DATABASE_NAME=backend_kb
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_HOST=knowledge_base_db
      # Knowledge base ml marketplace
      - ML_MARKET_PLACE_HOST=http://ml_marketplace
      - KNOWLEDGE_DB_URL=http://intent-tracker:7200
    networks:
      - internal_network

  intent-tracker:
    build:
      context: ./knowledge-base/intent-tracker
    environment:
      GDB_JAVA_OPTS: >-
        -Xmx2g -Xms2g
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.workbench.importDirectory=/opt/graphdb/home/graphdb-import
        -Dgraphdb.workbench.cors.enable=true
        -Denable-context-index=true
        -Dentity-pool-implementation=transactional
        -Dhealth.max.query.time.seconds=60
        -Dgraphdb.append.request.id.headers=true
        -Dreuse.vars.in.subselects=true
    ports:
      - 7200:7200
      - 7300:7300
    networks:
      - internal_network
      - default
    restart: unless-stopped
    volumes:
      - graphdb_data:/opt/graphdb/home

  knowledge_base_db:
    build:
      context: ./knowledge-base
    container_name: backend-knowledge-base
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    networks:
      - internal_network

  ml_marketplace:
    build:
      context: ./ml_marketplace
    container_name: backend-ml-marketplace
    restart: always
    networks:
      - internal_network

  policy_generator:
    build:
      context: ./policy-generator
    container_name: backend-policy-generator
    environment:
      - MANO_URL=http://51.145.254.19:8001
    restart: always
    networks:
      - default
      - internal_network

  data_manager:
    build:
      context: ./data-manager
    container_name: backend-data-manager
    restart: always
    ports:
      - "6001:6001"
    networks:
      - default
      - internal_network
      - data_manager_network
    environment:
      - INFLUX_DB_HOST=data_store
      - INFLUX_DB_PORT=8086
      - INFLUX_DB_ORG=scoring
      - INFLUX_DB_BUCKET=data-store
      - INFLUX_DB_TOKEN=bQsh6k7qAbhdX64ErcURpkWXXjahtQs3U4fU4jwUp4oOlqlnTtPiup847TKnp5M98BWUZMxyJM0P2heTsfo0FQ==

  data_store:
    build:
      context: ./data-manager/data-store
    container_name: data_manager_data_store
    volumes:
      - data_store:/var/lib/influxdb2
      - data_store_config:/etc/influxdb2
    ports:
      - "8086:8086"
    networks:
      - data_manager_network
      - default
  data_store_init:
    links:
      - data_store
    build:
      context: ./data-manager/data-store
      dockerfile: Init.Dockerfile
    volumes:
      # Mount for influxdb data directory and configuration
      - data_store:/var/lib/influxdb2
      - data_store_config:/etc/influxdb2
    restart: on-failure:10
    networks:
      - data_manager_network
    depends_on:
      - data_store

  intent_monitor:
    build:
      context: ./intent-monitor
    container_name: backend-intent-monitor
    environment:
      - INTENT_MANAGER_URL=http://intent_manager
      - DATA_MANAGER_URL=http://data_manager
    restart: always
    networks:
      - internal_network

volumes:
  pg_data:
  graphdb_data:
  data_store:
  data_store_config:
networks:
  data_manager_network:
  internal_network:
  default:
    driver: bridge
