FROM influxdb:2.3

# set environment variables 
ENV DOCKER_INFLUXDB_INIT_MODE=setup
ENV DOCKER_INFLUXDB_INIT_USERNAME=admin
ENV DOCKER_INFLUXDB_INIT_PASSWORD=dataStorePass
ENV DOCKER_INFLUXDB_INIT_ORG=scoring
ENV DOCKER_INFLUXDB_INIT_BUCKET=data-store
ENV DOCKER_INFLUXDB_INIT_RETENTION=1w
ENV DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=bQsh6k7qAbhdX64ErcURpkWXXjahtQs3U4fU4jwUp4oOlqlnTtPiup847TKnp5M98BWUZMxyJM0P2heTsfo0FQ==

COPY ./setup.sh ./setup.sh

ENTRYPOINT [ "./setup.sh" ]