version: "3.5"
services:
  intent-ingestion:
    build: ./intent-ingestion
    container_name: cfs-intent-ingestion
    ports:
      - "3000:3000"
    networks:
      - ingestion-network

  intent-recognition:
    build: ./intent-recognition-engine
    container_name: cfs-intent-recognition
    ports:
      - "5005:5005"
    networks:
      - recognition-network

  intent-recognition-actions:
    container_name: actions_server
    build: ./intent-recognition-engine/actions
    volumes:
      - "./intent-recognition-engine/actions:/app/actions"
    ports:
      - "5055:5055"
    networks:
      - recognition-network

  intent_store:
    container_name: cfs-intent_store
    image: postgres
    environment:
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - intent_store_network
    restart: unless-stopped

  intent_store_admin_panel:
    container_name: cfs-intent_store_admin_panel
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-akramboutouchent@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - intent_store_network
    restart: unless-stopped

networks:
  ingestion-network:
  recognition-network:
  intent_store_network:
    driver: bridge

volumes:
  postgres:
  pgadmin:
