replicaCount: {{ .ApplicationReplicaCount }}

# this represents the kube-ovn parameters
network:
  SubNetName: {{ .NetworkSubnetName}}
  podEgressRate: {{ .NetworkPodEgressRate}}
  podIngressRate: {{ .NetworkPodIngressRate}}

service:
  type: NodePort
  port: 80
  nodePort: 31000

resources:
  limits:
    cpu: {{ .CpuLimits }}m
    memory: {{ .MemoryLimits }}Mi
    ephemeral-storage: {{ .StorageLimits }}Mi
  requests:
    ephemeral-storage: {{ .StorageRequests }}Mi


